-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create items table
create table if not exists public.items (
    id uuid default uuid_generate_v4() primary key,
    title text not null,
    description text,
    price numeric(10,2) not null,
    image_url text,
    location text,
    seller_id uuid references auth.users(id) not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create todos table
create table if not exists public.todos (
    id bigint generated by default as identity primary key,
    title text not null,
    completed boolean default false,
    user_id uuid references auth.users(id) not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create messages table
create table if not exists public.messages (
    id uuid default uuid_generate_v4() primary key,
    content text not null,
    sender_id uuid references auth.users(id) not null,
    receiver_id uuid references auth.users(id) not null,
    is_read boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create profiles table
create table if not exists public.profiles (
    id uuid references auth.users(id) primary key,
    name text not null,
    university text,
    avatar_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create storage bucket for user uploads
insert into storage.buckets (id, name, public) values ('user-uploads', 'user-uploads', true);

-- Enable Row Level Security
alter table public.items enable row level security;
alter table public.todos enable row level security;
alter table public.messages enable row level security;
alter table public.profiles enable row level security;

-- Items policies
create policy "Anyone can view items"
    on public.items for select
    using (true);

create policy "Users can create their own items"
    on public.items for insert
    with check (auth.uid() = seller_id);

create policy "Users can update their own items"
    on public.items for update
    using (auth.uid() = seller_id);

create policy "Users can delete their own items"
    on public.items for delete
    using (auth.uid() = seller_id);

-- Todos policies
create policy "Users can view their own todos"
    on public.todos for select
    using (auth.uid() = user_id);

create policy "Users can create their own todos"
    on public.todos for insert
    with check (auth.uid() = user_id);

create policy "Users can update their own todos"
    on public.todos for update
    using (auth.uid() = user_id);

create policy "Users can delete their own todos"
    on public.todos for delete
    using (auth.uid() = user_id);

-- Messages policies
create policy "Users can view their own messages"
    on public.messages for select
    using (auth.uid() in (sender_id, receiver_id));

create policy "Users can send messages"
    on public.messages for insert
    with check (auth.uid() = sender_id);

create policy "Users can update their own sent messages"
    on public.messages for update
    using (auth.uid() in (sender_id, receiver_id));

create policy "Users can delete their own messages"
    on public.messages for delete
    using (auth.uid() = sender_id);

-- Profiles policies
create policy "Anyone can view profiles"
    on public.profiles for select
    using (true);

create policy "Users can update their own profile"
    on public.profiles for update
    using (auth.uid() = id);

-- Create function to automatically update updated_at
create or replace function public.handle_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

-- Create triggers for updated_at
create trigger handle_items_updated_at
    before update on public.items
    for each row
    execute function public.handle_updated_at();

create trigger handle_todos_updated_at
    before update on public.todos
    for each row
    execute function public.handle_updated_at();

create trigger handle_profiles_updated_at
    before update on public.profiles
    for each row
    execute function public.handle_updated_at();

-- Create function to handle new user profiles
create or replace function public.handle_new_user()
returns trigger as $$
begin
    insert into public.profiles (id, name, avatar_url)
    values (new.id, new.raw_user_meta_data->>'name', null);
    return new;
end;
$$ language plpgsql;

-- Create trigger for new user profiles
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user(); 